const WORDS = {

  hiragana: [
    // verbs
    {k:'たべる',r:'taberu',m:'to eat'},
    {k:'のむ',r:'nomu',m:'to drink'},
    {k:'ねる',r:'neru',m:'to sleep'},
    {k:'おきる',r:'okiru',m:'to wake up'},
    {k:'いく',r:'iku',m:'to go'},
    {k:'くる',r:'kuru',m:'to come'},
    {k:'かえる',r:'kaeru',m:'to return / go home'},
    {k:'みる',r:'miru',m:'to see / watch'},
    {k:'きく',r:'kiku',m:'to listen / ask'},
    {k:'はなす',r:'hanasu',m:'to speak / talk'},
    {k:'かく',r:'kaku',m:'to write'},
    {k:'よむ',r:'yomu',m:'to read'},
    {k:'かう',r:'kau',m:'to buy'},
    {k:'うる',r:'uru',m:'to sell'},
    {k:'つくる',r:'tsukuru',m:'to make / create'},
    {k:'する',r:'suru',m:'to do'},
    {k:'ある',r:'aru',m:'there is / to exist (things)'},
    {k:'いる',r:'iru',m:'to exist (animate)'},
    {k:'わかる',r:'wakaru',m:'to understand'},
    {k:'しる',r:'shiru',m:'to know'},
    {k:'おもう',r:'omou',m:'to think / feel'},
    {k:'はいる',r:'hairu',m:'to enter'},
    {k:'でる',r:'deru',m:'to exit / leave'},
    {k:'あける',r:'akeru',m:'to open'},
    {k:'しめる',r:'shimeru',m:'to close'},
    {k:'まつ',r:'matsu',m:'to wait'},
    {k:'あう',r:'au',m:'to meet'},
    {k:'あるく',r:'aruku',m:'to walk'},
    {k:'はしる',r:'hashiru',m:'to run'},
    {k:'つかう',r:'tsukau',m:'to use'},
    {k:'おぼえる',r:'oboeru',m:'to remember / memorize'},
    {k:'わすれる',r:'wasureru',m:'to forget'},
    {k:'おしえる',r:'oshieru',m:'to teach / tell'},
    {k:'ならう',r:'narau',m:'to learn'},
    {k:'やすむ',r:'yasumu',m:'to rest'},
    {k:'はたらく',r:'hataraku',m:'to work'},
    {k:'あそぶ',r:'asobu',m:'to play'},
    {k:'よぶ',r:'yobu',m:'to call / invite'},
    {k:'きる',r:'kiru',m:'to cut'},
    {k:'なる',r:'naru',m:'to become'},
    {k:'できる',r:'dekiru',m:'can / to be able to'},
    {k:'もつ',r:'motsu',m:'to hold / have'},
    {k:'かんがえる',r:'kangaeru',m:'to think / consider'},
    {k:'さがす',r:'sagasu',m:'to search / look for'},
    {k:'みつける',r:'mitsukeru',m:'to find'},
    {k:'てつだう',r:'tetsudau',m:'to help / assist'},
    {k:'おす',r:'osu',m:'to push'},
    {k:'ひく',r:'hiku',m:'to pull'},
    {k:'とまる',r:'tomaru',m:'to stop / stay'},
    {k:'すむ',r:'sumu',m:'to live / reside'},
    // body
    {k:'からだ',r:'karada',m:'body'},
    {k:'あたま',r:'atama',m:'head'},
    {k:'て',r:'te',m:'hand'},
    {k:'あし',r:'ashi',m:'foot / leg'},
    {k:'め',r:'me',m:'eye'},
    {k:'みみ',r:'mimi',m:'ear'},
    {k:'くち',r:'kuchi',m:'mouth'},
    {k:'はな',r:'hana',m:'nose (鼻)'},
    {k:'かお',r:'kao',m:'face'},
    {k:'こえ',r:'koe',m:'voice'},
    // nature
    {k:'みず',r:'mizu',m:'water'},
    {k:'ひ',r:'hi',m:'fire / day'},
    {k:'かぜ',r:'kaze',m:'wind'},
    {k:'あめ',r:'ame',m:'rain'},
    {k:'ゆき',r:'yuki',m:'snow'},
    {k:'そら',r:'sora',m:'sky'},
    {k:'うみ',r:'umi',m:'sea / ocean'},
    {k:'やま',r:'yama',m:'mountain'},
    {k:'かわ',r:'kawa',m:'river'},
    {k:'き',r:'ki',m:'tree'},
    {k:'はな',r:'hana',m:'flower (花)'},
    {k:'つち',r:'tsuchi',m:'earth / soil'},
    {k:'いし',r:'ishi',m:'stone / rock'},
    {k:'くさ',r:'kusa',m:'grass'},
    {k:'もり',r:'mori',m:'forest'},
    // time
    {k:'あさ',r:'asa',m:'morning'},
    {k:'ひる',r:'hiru',m:'noon / daytime'},
    {k:'よる',r:'yoru',m:'night'},
    {k:'きょう',r:'kyou',m:'today'},
    {k:'あした',r:'ashita',m:'tomorrow'},
    {k:'きのう',r:'kinou',m:'yesterday'},
    {k:'いま',r:'ima',m:'now'},
    {k:'まいにち',r:'mainichi',m:'every day'},
    {k:'とき',r:'toki',m:'time / moment'},
    {k:'はる',r:'haru',m:'spring'},
    {k:'なつ',r:'natsu',m:'summer'},
    {k:'あき',r:'aki',m:'autumn'},
    {k:'ふゆ',r:'fuyu',m:'winter'},
    // places
    {k:'いえ',r:'ie',m:'house / home'},
    {k:'へや',r:'heya',m:'room'},
    {k:'まち',r:'machi',m:'town / city'},
    {k:'みち',r:'michi',m:'road / path'},
    {k:'えき',r:'eki',m:'train station'},
    {k:'がっこう',r:'gakkou',m:'school'},
    {k:'びょういん',r:'byouin',m:'hospital'},
    {k:'みせ',r:'mise',m:'shop / store'},
    {k:'こうえん',r:'kouen',m:'park'},
    {k:'にわ',r:'niwa',m:'garden'},
    // people / relationships
    {k:'ひと',r:'hito',m:'person / people'},
    {k:'おとこ',r:'otoko',m:'man / male'},
    {k:'おんな',r:'onna',m:'woman / female'},
    {k:'こども',r:'kodomo',m:'child'},
    {k:'おとな',r:'otona',m:'adult'},
    {k:'ともだち',r:'tomodachi',m:'friend'},
    {k:'かぞく',r:'kazoku',m:'family'},
    {k:'せんせい',r:'sensei',m:'teacher'},
    {k:'がくせい',r:'gakusei',m:'student'},
    {k:'いしゃ',r:'isha',m:'doctor'},
    // objects
    {k:'もの',r:'mono',m:'thing / object'},
    {k:'ほん',r:'hon',m:'book'},
    {k:'かみ',r:'kami',m:'paper'},
    {k:'えんぴつ',r:'enpitsu',m:'pencil'},
    {k:'かばん',r:'kaban',m:'bag / briefcase'},
    {k:'くつ',r:'kutsu',m:'shoes'},
    {k:'ふく',r:'fuku',m:'clothes'},
    {k:'かさ',r:'kasa',m:'umbrella'},
    {k:'とけい',r:'tokei',m:'watch / clock'},
    {k:'かぎ',r:'kagi',m:'key / lock'},
    // food
    {k:'ごはん',r:'gohan',m:'rice / meal'},
    {k:'たまご',r:'tamago',m:'egg'},
    {k:'さかな',r:'sakana',m:'fish'},
    {k:'にく',r:'niku',m:'meat'},
    {k:'やさい',r:'yasai',m:'vegetable'},
    {k:'くだもの',r:'kudamono',m:'fruit'},
    {k:'おちゃ',r:'ocha',m:'green tea'},
    {k:'みそしる',r:'misoshiru',m:'miso soup'},
    {k:'すし',r:'sushi',m:'sushi'},
    {k:'そば',r:'soba',m:'buckwheat noodles'},
    // adjectives
    {k:'おおきい',r:'ookii',m:'big / large'},
    {k:'ちいさい',r:'chiisai',m:'small / little'},
    {k:'あたらしい',r:'atarashii',m:'new'},
    {k:'ふるい',r:'furui',m:'old (things)'},
    {k:'たかい',r:'takai',m:'tall / expensive'},
    {k:'ひくい',r:'hikui',m:'low / short (height)'},
    {k:'ながい',r:'nagai',m:'long'},
    {k:'みじかい',r:'mijikai',m:'short (length)'},
    {k:'おもい',r:'omoi',m:'heavy'},
    {k:'かるい',r:'karui',m:'light (weight)'},
    {k:'あつい',r:'atsui',m:'hot'},
    {k:'さむい',r:'samui',m:'cold (weather)'},
    {k:'つめたい',r:'tsumetai',m:'cold (to touch)'},
    {k:'はやい',r:'hayai',m:'fast / early'},
    {k:'おそい',r:'osoi',m:'slow / late'},
    {k:'たのしい',r:'tanoshii',m:'fun / enjoyable'},
    {k:'かなしい',r:'kanashii',m:'sad'},
    {k:'うれしい',r:'ureshii',m:'happy / glad'},
    {k:'こわい',r:'kowai',m:'scary'},
    {k:'むずかしい',r:'muzukashii',m:'difficult'},
    {k:'やさしい',r:'yasashii',m:'easy / kind'},
    {k:'おいしい',r:'oishii',m:'delicious'},
    {k:'いい',r:'ii',m:'good'},
    {k:'わるい',r:'warui',m:'bad'},
    {k:'おもしろい',r:'omoshiroi',m:'interesting / funny'},
    {k:'つまらない',r:'tsumaranai',m:'boring / dull'},
    {k:'ひろい',r:'hiroi',m:'wide / spacious'},
    {k:'せまい',r:'semai',m:'narrow / cramped'},
    {k:'あかるい',r:'akarui',m:'bright'},
    {k:'くらい',r:'kurai',m:'dark'},
    // common expressions / adverbs
    {k:'はい',r:'hai',m:'yes'},
    {k:'いいえ',r:'iie',m:'no'},
    {k:'ありがとう',r:'arigatou',m:'thank you'},
    {k:'すみません',r:'sumimasen',m:'excuse me / sorry'},
    {k:'ごめんなさい',r:'gomennasai',m:"I'm sorry"},
    {k:'おねがい',r:'onegai',m:'please (request)'},
    {k:'また',r:'mata',m:'again / also'},
    {k:'もう',r:'mou',m:'already / soon'},
    {k:'まだ',r:'mada',m:'not yet / still'},
    {k:'とても',r:'totemo',m:'very / extremely'},
    {k:'すこし',r:'sukoshi',m:'a little / a few'},
    {k:'たくさん',r:'takusan',m:'a lot / many'},
    {k:'いつも',r:'itsumo',m:'always'},
    {k:'ときどき',r:'tokidoki',m:'sometimes'},
    {k:'ぜんぶ',r:'zenbu',m:'all / everything'},
    {k:'もっと',r:'motto',m:'more'},
    {k:'たぶん',r:'tabun',m:'probably / maybe'},
    {k:'ほんとうに',r:'hontouni',m:'really / truly'},
    // question words / demonstratives
    {k:'なに',r:'nani',m:'what'},
    {k:'だれ',r:'dare',m:'who'},
    {k:'いつ',r:'itsu',m:'when'},
    {k:'どこ',r:'doko',m:'where'},
    {k:'どう',r:'dou',m:'how'},
    {k:'なぜ',r:'naze',m:'why'},
    {k:'いくつ',r:'ikutsu',m:'how many'},
    {k:'いくら',r:'ikura',m:'how much'},
    {k:'これ',r:'kore',m:'this'},
    {k:'それ',r:'sore',m:'that'},
    {k:'あれ',r:'are',m:'that (over there)'},
    {k:'ここ',r:'koko',m:'here'},
    {k:'そこ',r:'soko',m:'there'},
    {k:'あそこ',r:'asoko',m:'over there'},
    // abstract / emotional
    {k:'こころ',r:'kokoro',m:'heart / mind'},
    {k:'ゆめ',r:'yume',m:'dream'},
    {k:'いのち',r:'inochi',m:'life'},
    {k:'ちから',r:'chikara',m:'power / strength'},
    {k:'きもち',r:'kimochi',m:'feeling / mood'},
    {k:'いろ',r:'iro',m:'color'},
    {k:'おと',r:'oto',m:'sound / noise'},
    {k:'ひかり',r:'hikari',m:'light'},
    {k:'うた',r:'uta',m:'song'},
    {k:'はなし',r:'hanashi',m:'story / talk'},
  ],

  katakana: [
    // electronics / tech
    {k:'テレビ',r:'terebi',m:'television'},
    {k:'ラジオ',r:'rajio',m:'radio'},
    {k:'カメラ',r:'kamera',m:'camera'},
    {k:'パソコン',r:'pasokon',m:'personal computer'},
    {k:'スマートフォン',r:'sumaatofon',m:'smartphone'},
    {k:'インターネット',r:'intaanetto',m:'internet'},
    {k:'キーボード',r:'kiiboodo',m:'keyboard'},
    {k:'マウス',r:'mausu',m:'mouse (computer)'},
    {k:'プリンター',r:'purintaa',m:'printer'},
    {k:'スクリーン',r:'sukuriin',m:'screen'},
    {k:'リモコン',r:'rimokon',m:'remote control'},
    {k:'エアコン',r:'eakon',m:'air conditioner'},
    {k:'プログラム',r:'puroguramu',m:'program'},
    {k:'データ',r:'deeta',m:'data'},
    {k:'システム',r:'shisutemu',m:'system'},
    {k:'アプリ',r:'apuri',m:'app / application'},
    {k:'ゲーム',r:'geemu',m:'game'},
    // transport
    {k:'バス',r:'basu',m:'bus'},
    {k:'タクシー',r:'takushii',m:'taxi'},
    {k:'バイク',r:'baiku',m:'motorcycle'},
    {k:'エレベーター',r:'erebeetaa',m:'elevator'},
    {k:'エスカレーター',r:'esukareetaa',m:'escalator'},
    // accommodation / buildings
    {k:'ホテル',r:'hoteru',m:'hotel'},
    {k:'アパート',r:'apaato',m:'apartment'},
    {k:'マンション',r:'manshon',m:'condominium / flat'},
    // shopping / eating
    {k:'レストラン',r:'resutoran',m:'restaurant'},
    {k:'カフェ',r:'kafe',m:'cafe'},
    {k:'スーパー',r:'suupaa',m:'supermarket'},
    {k:'デパート',r:'depaato',m:'department store'},
    // food / drink
    {k:'アイスクリーム',r:'aisukuriimu',m:'ice cream'},
    {k:'ケーキ',r:'keeki',m:'cake'},
    {k:'パン',r:'pan',m:'bread'},
    {k:'バター',r:'bataa',m:'butter'},
    {k:'チーズ',r:'chiizu',m:'cheese'},
    {k:'コーヒー',r:'koohii',m:'coffee'},
    {k:'ジュース',r:'juusu',m:'juice'},
    {k:'ビール',r:'biiru',m:'beer'},
    {k:'ワイン',r:'wain',m:'wine'},
    {k:'ピザ',r:'piza',m:'pizza'},
    {k:'ハンバーガー',r:'hanbaagaa',m:'hamburger'},
    // furniture / home
    {k:'テーブル',r:'teeburu',m:'table'},
    {k:'ソファ',r:'sofa',m:'sofa / couch'},
    {k:'ベッド',r:'beddo',m:'bed'},
    {k:'ドア',r:'doa',m:'door'},
    {k:'カーテン',r:'kaaten',m:'curtain'},
    // kitchenware
    {k:'スプーン',r:'supuun',m:'spoon'},
    {k:'フォーク',r:'fooku',m:'fork'},
    {k:'コップ',r:'koppu',m:'cup / glass'},
    {k:'ボトル',r:'botoru',m:'bottle'},
    // clothing
    {k:'コート',r:'kooto',m:'coat'},
    {k:'ジャケット',r:'jaketto',m:'jacket'},
    {k:'シャツ',r:'shatsu',m:'shirt'},
    {k:'スニーカー',r:'suniikaa',m:'sneakers'},
    {k:'バッグ',r:'baggu',m:'bag / handbag'},
    // professions
    {k:'エンジニア',r:'enjinia',m:'engineer'},
    {k:'ドクター',r:'dokutaa',m:'doctor'},
    {k:'ナース',r:'naasu',m:'nurse'},
    {k:'マネージャー',r:'maneejaa',m:'manager'},
    // sports / fitness
    {k:'スポーツ',r:'supootsu',m:'sports'},
    {k:'サッカー',r:'sakkaa',m:'soccer'},
    {k:'テニス',r:'tenisu',m:'tennis'},
    {k:'バスケットボール',r:'basukettobooru',m:'basketball'},
    {k:'プール',r:'puuru',m:'swimming pool'},
    {k:'ジム',r:'jimu',m:'gym'},
    {k:'ダンス',r:'dansu',m:'dance'},
    // music / entertainment
    {k:'ミュージック',r:'myuujikku',m:'music'},
    {k:'ギター',r:'gitaa',m:'guitar'},
    {k:'ピアノ',r:'piano',m:'piano'},
    {k:'コンサート',r:'konsaato',m:'concert'},
    {k:'ニュース',r:'nyuusu',m:'news'},
    {k:'ドラマ',r:'dorama',m:'TV drama'},
    // work / study
    {k:'ミーティング',r:'miitingu',m:'meeting'},
    {k:'オフィス',r:'ofisu',m:'office'},
    {k:'プロジェクト',r:'purojekuto',m:'project'},
    {k:'チーム',r:'chiimu',m:'team'},
    {k:'リーダー',r:'riidaa',m:'leader'},
    {k:'スケジュール',r:'sukejuuru',m:'schedule'},
    {k:'レポート',r:'repooto',m:'report'},
    {k:'テスト',r:'tesuto',m:'test / exam'},
    // health / general
    {k:'ストレス',r:'sutoresu',m:'stress'},
    {k:'エネルギー',r:'enerugii',m:'energy'},
    {k:'アレルギー',r:'arerugii',m:'allergy'},
    {k:'ビタミン',r:'bitamin',m:'vitamin'},
    {k:'サービス',r:'saabisu',m:'service'},
    {k:'ボリューム',r:'boryuumu',m:'volume'},
  ],

};
